//@version=5
indicator(title=双均线交易指标, shorttitle="双均线交易指标", overlay=true)
// === 参数输入 ===
lenSMA1 = input.int(20, title = 'SMA1')
lenEMA1 = input.int(20, title = 'EMA1')
lenSMA2 = input.int(60, title = 'SMA2')
lenEMA2 = input.int(60, title = 'EMA2')
lenSMA3 = input.int(120, title = 'SMA3')
lenEMA3 = input.int(120, title = 'EMA3')

// === 均线计算 ===
sma1 = ta.sma(close, lenSMA1)
ema1 = ta.ema(close, lenEMA1)
sma2 = ta.sma(close, lenSMA2)
ema2 = ta.ema(close, lenEMA2)
sma3 = ta.sma(close, lenSMA3)
ema3 = ta.ema(close, lenEMA3)

// === 颜色定义 ===
sma1Color = color.rgb(255, 230, 100) // 浅黄
ema1Color = color.rgb(200, 160, 0) // 深黄
sma2Color = color.rgb(120, 200, 255) // 浅蓝
ema2Color = color.rgb(0, 80, 200) // 深蓝
sma3Color = color.rgb(255, 150, 150) // 浅红
ema3Color = color.rgb(223, 20, 241) // 深红

// === 绘制均线 ===
plot(sma1, color = sma1Color, title = 'SMA1', display = display.none)
plot(ema1, color = ema1Color, title = 'EMA1')
plot(sma2, color = sma2Color, title = 'SMA2', display = display.none)
plot(ema2, color = ema2Color, title = 'EMA2')
plot(sma3, color = sma3Color, title = 'SMA3', display = display.none)
plot(ema3, color = ema3Color, title = 'EMA3', display = display.none)